model_info:
  hidden_info: [64, 32]
  activ_info: ["relu","relu","linear"]
  method_init: "xavier_uniform" #options: "zero", "xavier_uniform"
train_method:
  type: "SGD" #options: "GD", "SGD"
  loss: "mse_loss"
  reg_layer: [0, 0, 0] #0 for no regularization for layer, 1 for L1 regularization for layer, 2 for L2 regularization for layer
  batch_size: 32
epochs: 30
learning_rate: 0.01
lambdas: [0.001,0.01,0.1,1]