defaults:
  - dataset: default
  - logger: wandb
  - search: default
  - model: default
  - _self_
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.model_info.hidden_info: '[128,64,32]'
      model.model_info.activ_info: '["relu","relu","relu","linear"]'
      model.train_method.type: SGD
      model.train_method.reg_layer: '[0,0,0,0],[1,1,1,1],[2,2,2,2],[0,0,0,1],[0,0,0,2],[1,1,1,0],[2,2,2,0],[1,1,1,2],[2,2,2,1]'
      logger.project: Regularization-layers-2
