defaults:
  - dataset: default
  - logger: wandb
  - search: default
  - model: default
  - _self_
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.train_method.reg_mode: L2
      model.train_method.type: SGD
      model.train_method.reg_layer: 1111
      logger.project: Test6